name: Ilk Test Pipeline

on:
    push:
        branches:
            - main

    workflow_dispatch:
    
jobs:
    artifacts-deneme-job:
      runs-on: ubuntu-latest
      steps:
          - name: Hello
            run: echo "hello world"
          
          - name: Dos
            run: echo "anan" >> anan.txt
           
          - name: Kontr
            run: cat anan.txt  