name: Ilk Test Pipeline

on:
    push:
        branches:
            - main

    workflow_dispatch:
    
jobs:
    artifacts-deneme-job:
      runs-on: ubuntu-latest
      steps:
          - name: Hello
            run: echo "hello world"
          
          - name: Dos
            run: echo "anan" >> anan.txt
           
          - name: Kontr
            run: cat anan.txt  
           
          - name: Artf
            uses: actions/upload-artifact@v4
            with:
              name: Report
              path: anan.txt  
    artifacts-deneme-job2:
      needs: artifacts-deneme-job
      runs-on: ubuntu-latest
      steps:
        - name: anan 3
          uses: actions/download-artifact@v4
          with:
            name: Rapor
            path: .

        - name: Test
          run: ls -la  