name: Ilk Test Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:
    
jobs:
    bek_ilk_job:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "Hello World"